apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: "true"
objects:
  - kind: Secret
    apiVersion: v1
    metadata:
      name: ${NAME}${SUFFIX}
    selector:
      deploymentconfig: ${NAME}${SUFFIX}
    stringData:
      CCW_userId: "${CCW_USER_ID}"
      CCW_guid: "${CCW_GUID}"
      CCW_directory: "${CCW_DIR}"
      CCW_endpointURL: "${CCW_ENDPOINT_URL}"
      CCW_applicationIdentifier: "${CCW_APP_ID}"
      CCW_basicAuth_username: "${CCW_USERNAME}"
      CCW_basicAuth_password: "${CCW_PASSWORD}"
    type: Opaque
parameters:
  - name: NAME
    displayName: Name
    description: Name
    required: true
    value: ccw
  - description: A name suffix used for all objects
    displayName: Suffix
    name: SUFFIX
    required: false
    value: "-dev"
  - name: CCW_USER_ID
    displayName: CCW_USER_ID
    description: CCW_USER_ID
    required: true
  - name: CCW_GUID
    displayName: CCW_GUID
    description: CCW_GUID
    required: true
  - name: CCW_DIR
    displayName: CCW_DIR
    description: CCW_DIR
    required: true
  - name: CCW_ENDPOINT_URL
    displayName: CCW_ENDPOINT_URL
    description: CCW_ENDPOINT_URL
    required: true
  - name: CCW_APP_ID
    displayName: CCW_APP_ID
    description: CCW_APP_ID
    required: true
  - name: CCW_USERNAME
    displayName: CCW_USERNAME
    description: CCW_USERNAME
    required: true
  - name: CCW_PASSWORD
    displayName: CCW_PASSWORD
    description: CCW_PASSWORD
    required: true
